# -*- coding: utf-8 -*-
"""E-commerce Proyek Analisis Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y_Go620RtbrLLSjkcgNvveh25cJM6NyG

# Proyek Analisis Data: [E-commerce Public Dataset]
- **Nama:** Cika Faza Fitra Akhirunnisa
- **Email:**  cikafaza@gmail.com
- **ID Dicoding:** cikafaza

## Menentukan Pertanyaan Bisnis

- **Pertanyaan 1**: Kategori produk mana saja yang mendapatkan jumlah penjualan terbaik dan jumlah penjualan terburuk berdasarkan jumlah order?
- **Pertanyaan 2:** Kapan perusahaan mengalami penjualan tertinggi berdasarkan jumlah order? dan apakah penjualan mengalami kenaikan terus menerus dari waktu ke waktu?
-  **Pertanyaan 3:** Jumlah customer paling banyak berada di kota mana saja?

##**Import Semua Packages/Library yang Digunakan**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""##**Data Wrangling**

## Gathering Data
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# opening datasets individually
orders = pd.read_csv('https://raw.githubusercontent.com/cikafaza/Proyek-Data-Analis-Dicoding/master/orders_dataset.csv')
items = pd.read_csv('https://raw.githubusercontent.com/cikafaza/Proyek-Data-Analis-Dicoding/master/order_items_dataset.csv')
products = pd.read_csv('https://raw.githubusercontent.com/cikafaza/Proyek-Data-Analis-Dicoding/master/products_dataset.csv')
payments = pd.read_csv('https://raw.githubusercontent.com/cikafaza/Proyek-Data-Analis-Dicoding/master/order_payments_dataset.csv')
reviews = pd.read_csv('https://raw.githubusercontent.com/cikafaza/Proyek-Data-Analis-Dicoding/master/order_reviews_dataset.csv')
customers = pd.read_csv('https://raw.githubusercontent.com/cikafaza/Proyek-Data-Analis-Dicoding/master/customers_dataset.csv')
sellers = pd.read_csv('https://raw.githubusercontent.com/cikafaza/Proyek-Data-Analis-Dicoding/master/sellers_dataset.csv')
geolocation = pd.read_csv('https://raw.githubusercontent.com/cikafaza/Proyek-Data-Analis-Dicoding/master/geolocation_dataset.csv')
category = pd.read_csv('https://raw.githubusercontent.com/cikafaza/Proyek-Data-Analis-Dicoding/master/product_category_name_translation.csv')

data = {'orders': orders,
        'items': items,
        'products': products,
        'payments': payments,
        'reviews': reviews,
        'customers': customers,
        'sellers': sellers,
        'geo': geolocation,
        'category': category}

data['customers'].head()

data['geo'].head()

data['items'].head()

data['payments'].head()

data['reviews'].head()

data['orders'].head()

data['products'].head()

data['sellers'].head()

data['category'].head()

"""## Assessing Data

####1. Data "customers"
"""

data['customers'].info()

"""#### semua tipe data "customers" sudah sesuai"""

# To calculate the number of missing values in a dataset
data['customers'].isna().sum()

"""pada data "customer" tidak ada missing value"""

# To calculate the total number of duplicate rows in a dataset
print(f'Duplicate count: {data['customers'].duplicated().sum()}')

"""pada data "customers" tidak ada yang duplicate

####2. Data "geo"
"""

data['geo'].info()

# To calculate the number of missing values in a dataset
data['geo'].isna().sum()

# To calculate the total number of duplicate rows in a dataset
print(f'Duplicate count: {data['geo'].duplicated().sum()}')

"""terdapat data yang duplicate sebanyak 261831

####3. Data "items"
"""

data['items'].info()

"""terdapat data type error di shipping_limit_date"""

# To calculate the number of missing values in a dataset
data['items'].isna().sum()

"""tidak ditemukan missing value di data "items"
"""

# To calculate the total number of duplicate rows in a dataset
print(f'Duplicate count: {data['items'].duplicated().sum()}')

"""tidak ada data duplicate di data "items"

####4. Data "payments"
"""

data['payments'].info()

"""tidak ada data type yang error di data "payments"
"""

# To calculate the number of missing values in a dataset
data['payments'].isna().sum()

"""tidak ada missing value di data "payments"
"""

# To calculate the total number of duplicate rows in a dataset
print(f'Duplicate count: {data['payments'].duplicated().sum()}')

"""tidak ada data duplicate di data"payments"

####5. Data "reviews"
"""

data['reviews'].info()

"""terdapat data type error pada review_creation_date dan review_answer_timestamp"""

# To calculate the number of missing values in a dataset
data['reviews'].isna().sum()

"""terdapat missing value di data review_comment_title dan review_comment_message"""

# To calculate the total number of duplicate rows in a dataset
print(f'Duplicate count: {data['reviews'].duplicated().sum()}')

"""tidak terdapat data duplicate di data "reviews"

####6. Data "orders"
"""

data['orders'].info()

"""terdapat dat type error pada order_delivered_carrier_date, order_delivered_customer_date, order_purchase_timestamp, dan order_approved_at, order_estimated_delivery_date. Seharusnya tipe data datetime"""

# To calculate the number of missing values in a dataset
data['orders'].isna().sum()

"""tedapat missing value di order_approved_at, order_delivered_carrier_date, order_delivered_customer_date"""

# To calculate the total number of duplicate rows in a dataset
print(f'Duplicate count: {data['orders'].duplicated().sum()}')

"""tidak ada data duplicate di data"orders"

####7. Data "products"
"""

data['products'].info()

# To calculate the number of missing values in a dataset
data['products'].isna().sum()

"""terdapat beberapa missing value pada data"products" kecuali dibagian product_id"""

# To calculate the total number of duplicate rows in a dataset
print(f'Duplicate count: {data['products'].duplicated().sum()}')

"""tidak ada data duplicate di data"products"

####8. Data "sellers"
"""

data['sellers'].info()

"""tidak ada data type yang error"""

# To calculate the number of missing values in a dataset
data['sellers'].isna().sum()

"""tidak ada missing value pada data "sellers"
"""

# To calculate the total number of duplicate rows in a dataset
print(f'Duplicate count: {data['sellers'].duplicated().sum()}')

"""tidak ada data duplicate di data "sellers"

####9. Data "category"
"""

data['category'].info()

"""data type tidak ada yang error"""

# To calculate the number of missing values in a dataset
data['category'].isna().sum()

"""tidak ada missing value di data "category"
"""

# To calculate the total number of duplicate rows in a dataset
print(f'Duplicate count: {data['category'].duplicated().sum()}')

"""tidak ada data duplicate di data "category"

## Cleaning Data

###1. Data type error in "items"
"""

# To access the columns that will be modified
datetime_columns = ['shipping_limit_date']

# To convert the previously accessed columns to datetime data type
for column in datetime_columns:
  items[column] = pd.to_datetime(items[column])

items.info()

"""###2. Data type error in "orders"
"""

# To access the columns that will be modified
datetime_columns = ['order_estimated_delivery_date','order_delivered_carrier_date', 'order_delivered_customer_date', 'order_approved_at', 'order_purchase_timestamp']

# To convert the previously accessed columns to datetime data type
for column in datetime_columns:
  orders[column] = pd.to_datetime(orders[column])

# To change the timestamp format in the `order_approved_at` column
orders['order_approved_at'] = orders['order_approved_at'].dt.strftime('%Y-%m-%d')
orders['order_approved_at'] = pd.to_datetime(orders['order_approved_at'])

orders.info()

"""###3. Data type error in "reviews"
"""

# To access the columns that will be modified
datetime_columns = ['review_creation_date', 'review_answer_timestamp']

# To convert the previously accessed columns to datetime data type
for column in datetime_columns:
  reviews[column] = pd.to_datetime(reviews[column])

reviews.info()

"""###4. Missing Values in "products"
"""

products[products.product_category_name.isna()]

products[products.product_weight_g.isna()]

products.dropna(inplace=True)

products.isna().sum()

"""###5. Null values in the order_approved_at column"""

# Filling missing values in 'order_approved_at' with the earliest available date.
min_date = orders['order_approved_at'].min()
orders['order_approved_at'].fillna(min_date, inplace=True)
orders.isna().sum()

"""###4. Remove duplicate data in "geo"
"""

# remove duplicate data
data['geo'].drop_duplicates(inplace=True)

"""## Exploratory Data Analysis (EDA)

### 1. Explore data "customers"
"""

#rangkuman parameter dari "customers"
data['customers'].describe(include='all')

# Persebaran jumlah pelanggan berdasarkan city
customers.groupby('customer_city').customer_id.nunique().sort_values(ascending=False)

# Persebaran jumlah pelanggan berdasarkan state
data['customers'].groupby(by="customer_state").customer_id.nunique().sort_values(ascending=False)

"""###2. Explore data "orders"
"""

orders.describe(include="all")

"""###3. Explore data "orders" dan "customers"
"""

# Menggabungkan data orders dengan data customers
orders_customers_df = pd.merge(
    left=data['customers'],
    right=data['orders'],
    how="left",
    left_on="customer_id",
    right_on="customer_id"
)
orders_customers_df.head()

# Jumlah order berdasarkan kota
orders_customers_df.groupby(by="customer_city").order_id.nunique().sort_values(ascending=False).reset_index().head(10)

"""### 4. Gabung data "products" dan "items"
"""

product_count_df = pd.merge(
    left = items,
    right = products,
    how = 'left',
    left_on = 'product_id',
    right_on = 'product_id'
)

product_count_english_df = pd.merge(
    left = product_count_df,
    right = category,
    how = 'left',
    left_on = 'product_category_name',
    right_on = 'product_category_name'
)

product_count_english_df.rename(columns={
    'order_id': 'total_order'
}, inplace=True)

product_count_english_df.groupby('product_category_name_english').total_order.nunique().sort_values(ascending=False).reset_index()

"""### 5. Gabung data "payments" dan "orders"
"""

total_revenue_df = pd.merge(
    left = orders,
    right = payments,
    how = 'left',
    left_on = 'order_id',
    right_on = 'order_id'
)
total_revenue_df.head()

revenue_by_day_df = total_revenue_df.groupby('order_approved_at').agg({
    'order_id': 'nunique',
    'payment_value': 'sum'
})
revenue_by_day_df.rename(columns={
    'order_id': 'total_order',
    'payment_value': 'total_revenue'
}, inplace=True)

revenue_by_day_df.reset_index(inplace=True)
revenue_by_day_df['order_approved_at'] = pd.to_datetime(revenue_by_day_df['order_approved_at'])

# Removing the last one as there was only one transaction in that month
last_month = revenue_by_day_df['order_approved_at'].max()
months_to_remove = (revenue_by_day_df['order_approved_at'] == last_month)
revenue_by_day_df = revenue_by_day_df[~months_to_remove]

revenue_by_day_df

"""###6. Gabung data "product" dan "category"
"""

products_category_df = pd.merge(
    left=data['products'],
    right=data['category'],
    how="left",
    left_on="product_category_name",
    right_on="product_category_name"
)
products_category_df.head()

products_category_df.groupby(by="product_category_name").product_id.nunique().sort_values(ascending=False).head(10)

products_category_df.groupby(by="product_category_name_english").product_id.nunique().sort_values(ascending=False).head(10)

"""###7. Gabung data "payments" dan "review"
"""

payments_reviews_df = pd.merge(
    left=data['payments'],
    right=data['reviews'],
    how="left",
    left_on="order_id",
    right_on="order_id"
)
payments_reviews_df.head()

payments_reviews_df.sort_values(by="payment_value", ascending=False)

payments_reviews_df.groupby(by="payment_type").agg({
    "order_id": "nunique",
    "payment_value":  ["min", "max"]
})

"""###8. Gabung data "items" dan "orders"
"""

items_orders_df = pd.merge(
    left=data['items'],
    right=data['orders'],
    how="left",
    left_on="order_id",
    right_on="order_id"
)
payments_reviews_df.head()

"""## Visualization & Explanatory Analysis

### **Pertanyaan 1**: Kategori produk mana saja yang mendapatkan jumlah penjualan terbaik dan jumlah penjualan terburuk berdasarkan jumlah order?
"""

data=product_count_english_df.groupby('product_category_name_english').total_order.nunique().sort_values(ascending=False).reset_index().head(5)
data.rename(columns={
    'order_id': 'total_order'
}, inplace=True)

data

data=product_count_english_df.groupby('product_category_name_english').total_order.nunique().sort_values(ascending=True).reset_index().head(5)
data.rename(columns={
    'order_id': 'total_order'
}, inplace=True)

data

fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(25, 8))
colors = ["#FA968F", "#2795F5", "#2795F5", "#2795F5", "#2795F5"]

sns.barplot(
    x='total_order', y='product_category_name_english',
    data=product_count_english_df.groupby('product_category_name_english').total_order.nunique().sort_values(ascending=False).reset_index().head(5),
    palette=colors, ax=ax[0])
ax[0].set_ylabel('Kategori Produk', fontsize=16)
ax[0].set_xlabel('Jumlah Order', fontsize=16)
ax[0].set_title('Produk dengan Penjualan Terbaik', fontsize=20)
ax[0].tick_params(axis='y', labelsize=18)
ax[0].tick_params(axis='x', labelsize=18)

sns.barplot(
    x='total_order', y='product_category_name_english',
    data=product_count_english_df.groupby('product_category_name_english').total_order.nunique().sort_values(ascending=True).reset_index().head(5),
    palette=colors, ax=ax[1])
ax[1].set_ylabel('Kategori Produk', fontsize=16)
ax[1].set_xlabel('Jumlah Order', fontsize=16)
ax[1].invert_xaxis()
ax[1].yaxis.tick_right()
ax[1].yaxis.set_label_position('right')
ax[1].set_title('Produk dengan Penjualan Terburuk', fontsize=20)
ax[1].tick_params(axis='y', labelsize=18)
ax[1].tick_params(axis='x', labelsize=18)

plt.suptitle('Produk dengan Jumlah Penjualan Terbaik dan Terburuk', fontsize=24)
plt.show()

"""**Produk dengan Penjualan Terbaik:**
1. bed_bath_table
2. health_beauty
3. sports_leisure
4. computers_accessories
5. furniture_decor


**Produk dengan Penjualan Terburuk:**
1. security_and_services
2. fashion_childrens_clothes
3. cds_dvds_musicals
4. la_cuisine
5. arts_and_craftmanship

### **Pertanyaan 2**:Kapan perusahaan mengalami penjualan tertinggi berdasarkan jumlah order? dan apakah penjualan mengalami kenaikan terus menerus dari waktu ke waktu?
"""

monthly_revenue_df = revenue_by_day_df.resample(rule='M', on='order_approved_at').agg({
    'total_order': 'sum',
    'total_revenue': 'sum'
})
monthly_revenue_df.index = monthly_revenue_df.index.strftime('%Y-%m')
monthly_revenue_df = monthly_revenue_df.reset_index()

monthly_revenue_df = monthly_revenue_df[monthly_revenue_df['order_approved_at'] != monthly_revenue_df['order_approved_at'].max()]

plt.figure(figsize=(12,5))
plt.plot(monthly_revenue_df['order_approved_at'],
         monthly_revenue_df['total_order'],
         marker='s', color='c')
plt.title('Jumlah Penjualan per Bulan (2016/09 - 2018/07)', fontsize=16)
plt.xlabel('Bulan dan Tahun', fontsize=10)
plt.ylabel('Jumlah Penjualan', fontsize=10)
plt.xticks(rotation=45)
plt.show()

"""### **Pertanyaan 3:** Jumlah customer paling banyak berada di kota mana saja?"""

bystate_df = orders_customers_df.groupby("customer_city").customer_id.nunique().reset_index().sort_values(by='customer_id', ascending=False).head(5)
bystate_df.rename(columns={
    "customer_id": "customer_count"
}, inplace=True)
bystate_df

plt.figure(figsize=(15, 5))
colors_ = ["#FA968F", "#2795F5", "#2795F5", "#2795F5", "#2795F5"]
sns.barplot(
    x="customer_count",
    y="customer_city",
    data=bystate_df.sort_values(by="customer_count", ascending=False),
    palette=colors_
)
plt.title("Jumlah Customer Berdasarkan City", loc="center", fontsize=15)
plt.ylabel("City Name")
plt.xlabel("Customer Count")
plt.tick_params(axis='y', labelsize=12)
plt.show()

"""## Analisis Lanjutan (Opsional)"""

rfm_df = items_orders_df.groupby(by="customer_id", as_index=False).agg({
    "order_approved_at": "max", #mengambil tanggal order terakhir
    "order_id": "nunique",
    "price": "sum"
})
rfm_df.columns = ["customer_id", "max_order_timestamp", "frequency", "monetary"]
rfm_df.head()

# menghitung kapan terakhir pelanggan melakukan transaksi (hari)
rfm_df["max_order_timestamp"] = rfm_df["max_order_timestamp"].dt.date
recent_date = orders["order_approved_at"].dt.date.max()
rfm_df["recency"] = rfm_df["max_order_timestamp"].apply(lambda x: (recent_date - x).days)
rfm_df.head()

rfm_df.drop("max_order_timestamp", axis=1, inplace=True)
rfm_df.head()

rfm_df.describe()

rfm_df.sort_values(by="recency", ascending=True).head(5)

rfm_df.sort_values(by="frequency", ascending=False).head(5)

fig, ax = plt.subplots(nrows=1, ncols=1, figsize=(15, 6))

colors = ["#2795F5", "#2795F5", "#2795F5", "#2795F5"]

sns.barplot(y="recency", x="customer_id", data=rfm_df.sort_values(by="recency", ascending=True).head(5), palette=colors, ax=ax)
ax.set_ylabel("Recency (days)")
ax.set_xlabel("Customer id")
ax.set_title("By Recency (days)", loc="center", fontsize=16)
ax.tick_params(axis ='x', labelsize=14)
plt.xticks(rotation=45)

plt.suptitle("Best Customer Based on RFM Parameters (customer_id)", fontsize=20)
plt.show()

fig, ax = plt.subplots(nrows=1, ncols=1, figsize=(15, 6))

colors = ["#2795F5", "#2795F5", "#2795F5", "#2795F5", "#2795F5"]

sns.barplot(y="frequency", x="customer_id", data=rfm_df.sort_values(by="frequency", ascending=False).head(5), palette=colors, ax=ax)
ax.set_ylabel("Frequency")
ax.set_xlabel("Customer id")
ax.set_title("By Frequency", loc="center", fontsize=16)
ax.tick_params(axis='x', labelsize=14)
plt.xticks(rotation=45)

plt.suptitle("Best Customer Based on RFM Parameters (customer_id)", fontsize=20)
plt.show()

fig, ax = plt.subplots(nrows=1, ncols=1, figsize=(15, 6))

colors = ["#2795F5", "#2795F5", "#2795F5", "#2795F5", "#2795F5"]

sns.barplot(y="monetary", x="customer_id", data=rfm_df.sort_values(by="monetary", ascending=False).head(5), palette=colors, ax=ax)
ax.set_ylabel("Monetary")
ax.set_xlabel("Customer id")
ax.set_title("By Monetary", loc="center", fontsize=16)
ax.tick_params(axis='x', labelsize=14)
plt.xticks(rotation=45)

plt.suptitle("Best Customer Based on RFM Parameters (customer_id)", fontsize=20)
plt.show()

"""##Mengurutkan customer berdasarkan recency, frequency, & monetary score"""

rfm_df['r_rank'] = rfm_df['recency'].rank(ascending=False)
rfm_df['f_rank'] = rfm_df['frequency'].rank(ascending=True)
rfm_df['m_rank'] = rfm_df['monetary'].rank(ascending=True)

rfm_df.head()

# normalizing the rank of the customers
rfm_df['r_rank_norm'] = (rfm_df['r_rank']/rfm_df['r_rank'].max())*100
rfm_df['f_rank_norm'] = (rfm_df['f_rank']/rfm_df['f_rank'].max())*100
rfm_df['m_rank_norm'] = (rfm_df['m_rank']/rfm_df['m_rank'].max())*100

rfm_df.drop(columns=['r_rank', 'f_rank', 'm_rank'], inplace=True)

rfm_df.head()

rfm_df['RFM_score'] = 0.15*rfm_df['r_rank_norm']+0.28 * \
    rfm_df['f_rank_norm']+0.57*rfm_df['m_rank_norm']
rfm_df['RFM_score'] *= 0.05
rfm_df = rfm_df.round(2)
rfm_df[['customer_id', 'RFM_score']].head(7)

"""##Segmentasi customer berdasarkan RFM_score"""

rfm_df["customer_segment"] = np.where(
    rfm_df['RFM_score'] > 4.5, "Top customers", (np.where(
        rfm_df['RFM_score'] > 4, "High value customer",(np.where(
            rfm_df['RFM_score'] > 3, "Medium value customer", np.where(
                rfm_df['RFM_score'] > 1.6, 'Low value customers', 'lost customers'))))))

rfm_df[['customer_id', 'RFM_score', 'customer_segment']].head(15)

customer_segment_df = rfm_df.groupby(by="customer_segment", as_index=False).customer_id.nunique()
customer_segment_df

customer_segment_df['customer_segment'] = pd.Categorical(customer_segment_df['customer_segment'], [
    "lost customers", "Low value customers", "Medium value customer",
    "High value customer", "Top customers"
])

plt.figure(figsize=(10, 5))
colors_ = ["#FA968F", "#FA968F", "#2795F5", "#2795F5", "#2795F5"]

sns.barplot(
    x="customer_id",
    y="customer_segment",
    data=customer_segment_df.sort_values(by="customer_segment", ascending=False),
    palette=colors_
)
plt.title("Number of Customer for Each Segment", loc="center", fontsize=18)
plt.ylabel("Customer Segment")
plt.xlabel("Customer id")
plt.tick_params(axis='y', labelsize=12)
plt.show()

"""## Conclusion

**1. Pertanyaan:** Kategori produk mana saja yang mendapatkan jumlah penjualan terbaik dan jumlah penjualan terburuk berdasarkan jumlah order?

  **Jawaban:**


*   **Produk dengan Penjualan Terbaik:**
1. bed_bath_table
2. health_beauty
3. sports_leisure
4. computers_accessories
5. furniture_decor



*   **Produk dengan Penjualan Terburuk:**
1. security_and_services
2. fashion_childrens_clothes
3. cds_dvds_musicals
4. la_cuisine
5. arts_and_craftmanship

**2.   Pertanyaan**: Kapan perusahaan mengalami penjualan tertinggi berdasarkan jumlah order? dan apakah penjualan mengalami kenaikan terus menerus dari waktu ke waktu?


**Jawaban:**

*   Berdasarkan grafik yang dihasilkan, dapat diketahui bahwa **penjualan tertinggi**
terjadi pada **tahun 2017 bulan November (2017-11)**.

*   Pada grafik tersebut dapat dilihat bahwa alur grafik secara sekilas mengalami kenaikan, akan tetapi ketika dilihat secara mendetail ternyata terdapat beberapa titik yang mengalami penurunan. Sehingga, dapat dikatakan penjualan toko tersebut **tidak selalu mengalami kenaikan penjualan dari tahun ke tahun.**

**3. Pertanyaan:** Jumlah customer paling banyak berada di kota mana saja?

**Jawaban:**
Berdasarkan grafik diatas dapat diketahui 5 kota yang memiliki jumlah customer tertinggi, yaitu:
*   Sao Paulo (15540)
*   Rio de Janeiro (6882)
*   Belo Horizonte (2773)
*   Brasilia (2131)
*   Curitiba (1521)
"""